### PR TITLE
Modernized + CDN enabled Project Template

### PR DESCRIPTION
**Pull request by mythz**
Hi Sebastian,

First of all I want to say thanks for creating & maintaining this community template which is much appreciated 👍 

For our next upcoming release we're focused on CDN capable [jamstack.org](https://jamstack.org) project templates since they provide the best end-user UX, an example of this is in our new [NetCoreTemplates/nextjs](https://github.com/NetCoreTemplates/nextjs) where a copy of the static UI generated Assets is published on GitHub Pages CDN at:

 - https://nextjs-gh.web-templates.io

Whilst the complete .NET App is deployed at:

 - https://nextjs.web-templates.io

> which also provides the `/api` backend for the CDN website above

We've added some docs for setting up [GitHub Action Deployments](https://nextjs.web-templates.io/posts/deploy) which effectively can be done by just adding GitHub Action Secrets (after a 1-time setup on a vanilla Linux box). I've also added docs with [benefits of this CDN approach](https://nextjs.web-templates.io/hosting).

As Blazor WASM is also capable of it, we'd also like to include this template in our list of CDN capable JAMStack-like templates, which the included `.github/workflows` actions and `.deploy` Docker templates enable.

Which this PR of my local fork makes use of to deploy the latest template to:

 - https://blazor-wasm-gh.web-templates.io (GitHub Pages CDN)
 - https://blazor-wasm.web-templates.io (.NET App)

The other major changes were aimed at upgrading to use the latest .NET 6 template features, e.g. top-level program with Hosting Startup modules, enabling nullable in host projects. 

Other changes were to improve the ergonomics for calling and binding to ServiceStack APIs, e.g. in the latest v5.13.3+ I've added a new [ApiResult.cs](https://github.com/ServiceStack/ServiceStack/blob/master/src/ServiceStack.Client/ApiResult.cs) which effectively wraps an API Success or Error Response and makes it easier to call APIs and handle its Success/Error results an example of this is in [CallHelloSecure.razor](https://github.com/ServiceStackApps/blazor-wasm-servicestack/blob/master/MyApp.Client/Pages/CallHelloSecure.razor):

```csharp
<input type="text" placeholder="What's your name?" @bind-value="request.Name" />
<button class="btn-primary" @onclick="CallApi">Go!</button>

@if (apiResult.ErrorMessage != null) {
    <h3 class="text-danger mt-2">@apiResult.ErrorMessage</h3>
}
else if (apiResult.Response != null) {
    <h3 class="text-success mt-2">@apiResult.Response.Result</h3>
}

@code {
    private HelloSecure request = new() {
        Name = "Blazor WASM"
    };

    private ApiResult<HelloResponse> apiResult = new();

    private async Task CallApi() => apiResult = await ApiAsync(request);
}
```

And in [Login.razor](https://github.com/ServiceStackApps/blazor-wasm-servicestack/blob/master/MyApp.Client/Pages/Login.razor) which enabling a form with validation binding looks something like:

```razor
<div class="container">
    <div class="row">
        <form submit=false class=@ClassNames("col-sm-6", apiResult.IsError ? " was-validated" : "")>
            @if (apiResult.ErrorSummary != null)
            {
                <div class="mb-3 alert alert-danger" role="alert">@apiResult.ErrorSummary</div>
            }

            <div class="mb-3">
                <label for="userName">Email address</label>
                <input type="email" id="userName" placeholder="Enter email" @bind-value="@Email" required
                       class=@ClassNames("form-control", apiResult.InvalidClass(nameof(Authenticate.UserName)))>
                <div class="invalid-feedback">@(apiResult.FieldErrorMessage(nameof(Authenticate.UserName)))</div>
            </div>
            <div class="mb-3">
                <label for="password">Password</label>
                <input type="password" id="password" placeholder="Password" @bind-value="@Password" required
                       class=@ClassNames("form-control", apiResult.InvalidClass(nameof(Authenticate.Password)))>
                <div class="invalid-feedback">@(apiResult.FieldErrorMessage(nameof(Authenticate.Password)))</div>
            </div>

            <button type="submit" class="mb-3 btn btn-primary" @onclick:preventDefault @onclick="LoginAsync">Login</button>
        </form>

        <div class="mt-4">
            Quick Link:
            <button class="btn btn-secondary" @onclick='e => SetUser("admin@localhost.local", "p@55wOrd")'>admin@localhost.local</button>
        </div>
    </div>
</div>
```

Where we can get rid of most instant properties by just modifying the `apiResult` which is automatically populated when calling APIs via `ApiAsync` or you can add local errors to as done below:

```csharp
@code {
    private ApiResult<AuthenticateResponse> apiResult = new();

    private string Email { get; set; } = "";
    private string Password { get; set; } = "";

    private void SetUser(string email, string password)
    {
        Email = email;
        Password = password;
    }

    private async Task LoginAsync()
    {
        apiResult.Reset();
        var emailEmpty = Email.IsNullOrEmpty();
        var passwordEmpty = Password.IsNullOrEmpty();
        if (emailEmpty)
        {
            apiResult.AddFieldError(nameof(Authenticate.UserName), "Email is required");
        }
        if (passwordEmpty)
        {
            apiResult.AddFieldError(nameof(Authenticate.Password), "Password is required");
        }
        if (emailEmpty || passwordEmpty) return;

        apiResult = await provider.Login(Email, Password);

        if (apiResult.IsSuccess)
        {
            var returnUrl = NavigationManager.QueryString("return");
            if (returnUrl.IsNullOrEmpty())
                returnUrl = "/";
            NavigationManager.NavigateTo(returnUrl!, true);
        }
    }
} 
```

We could've also simplified & removed the `Email` and `Password` instance property as done in `CallHelloSecure.razor` above by just deep binding to the request DTO, e.g. something like:

```razor
<input type="text" placeholder="What's your name?" @bind-value="request.Name" />

<div class="mb-3">
    <label for="userName">Email address</label>
    <input type="email" id="userName" placeholder="Enter email" @bind-value="request.UserName" required
           class=@ClassNames("form-control", apiResult.InvalidClass(nameof(Authenticate.UserName)))>
    <div class="invalid-feedback">@(apiResult.FieldErrorMessage(nameof(Authenticate.UserName)))</div>
</div>

@code {
    private Authenticate request = new();

    private async Task SubmitAsync() => apiResult = await ApiAsync(request);
}
```

But as it needs to call `provider.Login(Email, Password)` instead of sending the Request DTO I've just left it as instance properties, but we no longer need to maintain separate field validation properties since we can resolve them from ApIResult APIs.

Anyway hopefully you'll accept this PR and general direction, I'm also happy to answer any questions about the template.

If you do accept these changes and make me an Admin I can add the necessary GitHub Action Secrets to this repo so any changes to this template are automatically deployed to https://blazor-wasm-gh.web-templates.io and  https://blazor-wasm.web-templates.io (which are currently tied to my fork).

### CODE REVIEW

**Comment by mythz** [comment]
Hi Sebastian,

I ended up doing a lot more work on Blazor support and this template as I can see the potential for using Blazor WASM for LOB apps. As a result I've started developing a new ServiceStack.Blazor project that encapsulates any blazor specific functionality and recommendations, e.g. as using `IHttpClientFactory`  is recommended I've switched to using a new API to register a Blazor Service Client:

```csharp
builder.Services.AddBlazorApiClient(builder.Configuration["ApiBaseUrl"] ?? builder.HostEnvironment.BaseAddress);
```

Which registers a JSON Service Client as a Typed HttpClient and also enables ability to make CORS requests.

The library also currently includes components `<ErrorSummary/>` and `<ErrorField>` components used in form binding and validation. The components are going to support both Bootstrap5 (default) as well as Apps that use Tailwind by changing the theme with:

```csharp
BlazorConfig.Theme = Theme.Tailwind; 
```

To help illustrate ServiceStack dev workflow examples I've added a TodosMVC App:

https://blazor-wasm.jamstacks.net/todomvc

As well a simple UI for our earlier multi-user [Bookings CRUD](https://docs.servicestack.net/autoquery-crud-bookings) demo where you can create complete CRUD Apps with just declarative AutoQuery DTOs (i.e. without Service impls) at:

https://blazor-wasm.jamstacks.net/bookings-crud

As I can see Blazor WASM is something we'll be investing more in future I've decided to make it a first class template instead of opening a PR for each change which slows down dev velocity. I'll still list your project template on our websites should you choose to take it in a different direction.

I'm happy to answer any questions about the templates & Blazor direction.

**Comment by nukedbit** [comment]
Hi @mythz sorry for answering so late, but i didn't get the notification.
I really appreciate the update, in the end for me is great if you get to include a Blazor Template as a default in the ServiceStack ecosystem, less burden for me and less waiting for the community :)  
When is ready le me know so i can redirect users to it.

What i had in mind for the blazor template but never had time for it , is to have a default user management ux using AdminUser features, and a default crud ux as base starting point to develop on , like what i see on you bookings crud demo.

Thanks again for letting me know you are working on it

**Comment by mythz** [comment]
ok cool, if that case yeah I'm happy to promote it as an official template over at [NetCoreTemplates/blazor-wasm](https://github.com/NetCoreTemplates/blazor-wasm).

I've already added a Sign Up / Register page at: https://blazor-wasm.jamstacks.net/signup

But yeah I should be able to add a quick CRUD User Management example that uses [AdminUsersFeature](https://docs.servicestack.net/admin-users#installation).

**Comment by mythz** [comment]
FYI I've implemented the Admin UI that's now shipping in the default template
demo: https://blazor-wasm.jamstacks.net/admin/users

It works with the same default fields added by default, where if you only needed to add support for an additional field you can use the collection initializer syntax to append it to the default fields, e.g:

```csharp
Plugins.Add(new AdminUsersFeature {
    QueryUserAuthProperties = {
        nameof(AppUser.Department),
    },
    UserFormLayout = {
        new() { Input.For<AppUser>(x => x.Department) },
    }
});
```

But for the [Configure.AuthRepository.cs](https://github.com/NetCoreTemplates/blazor-wasm/blob/main/MyApp/Configure.AuthRepository.cs) I've decided to override the defaults to showcase its new flexibility features where each fields appearance and behavior is highly customizable on the server plugin registration, e.g:

```csharp
Plugins.Add(new AdminUsersFeature {
    
    // Show custom fields in Search Results
    QueryUserAuthProperties = new() {
        nameof(AppUser.Id),
        nameof(AppUser.Email),
        nameof(AppUser.DisplayName),
        nameof(AppUser.Department),
        nameof(AppUser.CreatedDate),
        nameof(AppUser.LastLoginDate),
    },

    // Support for responsive layouts by hiding columns at different media sizes:
    QueryMediaRules = new()
    {
        MediaRules.ExtraSmall.Show<AppUser>(x => new { x.Id, x.Email, x.DisplayName }),
        MediaRules.Small.Show<AppUser>(x => x.Department),
    },

    // Add Custom Fields to Create/Edit User Forms
    UserFormLayout = new() {
        new()
        {
            Input.For<AppUser>(x => x.Email),
        },
        new()
        {
            Input.For<AppUser>(x => x.DisplayName),
        },
        new()
        {
            Input.For<AppUser>(x => x.Company),
            Input.For<AppUser>(x => x.Department),
        },
        new() {
            Input.For<AppUser>(x => x.PhoneNumber, c => c.Type = Input.Types.Tel)
        },
        new() {
            Input.For<AppUser>(x => x.Nickname, c => {
                c.Help = "Public alias visible to others (3-12 lower alpha numeric chars)";
                c.Pattern = "^[a-z][a-z0-9_.-]{3,12}$";
                //c.Required = true;
            })
        },
        new() {
            Input.For<AppUser>(x => x.ProfileUrl, c => c.Type = Input.Types.Url)
        },
        new() {
            Input.For<AppUser>(x => x.IsArchived), Input.For<AppUser>(x => x.ArchivedDate),
        },
    }
});
```

Which generates the Custom UI in the default template:

image

**Pull request closed without merging**
